apiVersion: v1
kind: Secret
metadata:
    name: crossplane-azure-credentials
stringData:
    azure-credentials.json: ENC[AES256_GCM,data:iwrpRP+jVzL1e2z1K2Fd2hV3fUrxzOMYH3fqwNyhxXF5WoX7cjgxTehDouloVvau06VQ12aujvBx9QtvYX/VlXEHwQKWaSQJBy7058FYDmFnZe4nSVK5yBa7C3a7ge5fQDK6VbbQiUdhSC61ZCT9gP6OWehswoBjKEeTuBgj2OIha5S2q6r7pTjG2b/DTl8AsFhQ/TaLebPOrdemFHkRCv5aeJG5d0OKGOxpY28d0LnuxlOrSJmxByfeBT+XsoQBwxRRH3xurylPO4QgwjtOHFtjvW+0zACWg5TRWDRaRHbUeh17r6zjkmqdA/plYuSgBmCgL2j03yessyYEybVC2La7szfVHScCI3ixFf/c6dz+WejCU4THFwUd/SB3+S6JLVDWfNyDc7WWkVGlQWHR4Xp2iT94VqLFVqT5oiJGcb/bJ/HmhoNQsm1jYGdNyGX2xPkeqVUD5hEdNvv3/WLHt8Z39+RdOQTFZSZBrZmwOn0TNWx6AiPVf3A+FjloV44EkNn4QgIqbkf9McnhpGzI6EQYoB1MwFJNtsG6y3BlAAmHqv6THP8yzgDtvrDZxs12L1Yx2Wv6xd9Fr1tCzh7nwv8ls/BvQuXlugx7SQcKX3kmTsf1BEzkpMw8zISou0RizpJfZZYP62/gRkt29IY0qzo1kFAkErVX7s9NBnM8U6WlUK45PMMTb7/e5/E8laMjHN82GaQBi2Kjl2nvS2Mr8wIuYIwLygzf3iCwSYng0BMPjVhJGwmlNERCcDv65iSRn29Pq9Ii8+5DfsvLgfV4zM8fn8DGuyU102c8DzvWDtAOXgeIGH0cKao/olPpkcXy23eJxESy7hcB7i8cMqsSQh1cxgqHouc5,iv:GpWr0jR8/IJ7laDe5WVzB0cfbh1hujqy2ZDC5clskeM=,tag:/NLeWkZYueMgWJ/qn155OA==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b3NHNHpRTHExOW0zTEdv
            dVpScG1TbkJPUFA3cHM0RVZjM2luS0ErLzJnClk1UFpBZTBDZkNkM1V3bU8zTlBO
            OEdxNHBpT1hMYWxiVk9laTlOTTRUQ0kKLS0tIEtRWnA3TWIzejFYY3hLYVhuSVNl
            Q3JIZXZxVTRBWDNsWERtaWtkbkZ6QzgKrDaS8ko8o2oabyyCnZOATQpUox1aiSiJ
            GGGsiiyfKsv6z7ysXZHE5ytXVV22ehaHrBrZbep1SQ/mHludWCguHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2026-01-16T09:30:48Z"
    mac: ENC[AES256_GCM,data:nj3AiQmS5ja35DTpDeTeOtYdcrFgeEMdRWGGj5YESULcToeW9j0WS1CXN22sN7rOWaeMgtbPKYjY7C9y0bw71IjYG+IUPbUf9Q6RpqeZI+4m9ACIcIyJRoBs7Lp5lRVDy7IwgeVeExXyji5HCVfUpdEN+eJwpqxSDHtpVUoQxtg=,iv:07WL3yFKoAgQe7YO6ocXbFdDSmXI5rxhj7s/bJUSir4=,tag:l+T+IZPc2VJA0h987mTgFg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
