apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:Iox4S47YvopDpOxbYn/dRSjJ8lg3xXBR5ocS6cCUJghU4yU9bkIR1g==,iv:dnrpwcPF5cAXjqEq9tRmkoYPlPXoeKALIvQq/Uw/RUI=,tag:aL+LVp/us/zO2DEKKXnjOA==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZXluNGl1dmpNZTFGZENo
            Q2VuaFArRHJmUmFqeXdpM0ZaZDNsRzI3cTNNCmgyNE1kS1pnS3hETmQyZERLNE1Z
            TEZGL00yUUxscnFyeFFpaG9ZSzBDVmcKLS0tIFFRVFMxNGFNSityMjI2N1ljUGY2
            ZGR1TjNHNmlpSTdWd2ZLakVJODYyYzQKlp09zuQ0zHlmVjJVpksiyHrR5xDYlH/y
            kqKkyAq8ZMHmqF0c1hcoApx83EgRK7+yCwzqLsKNrf8hRiLhGq/gZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-23T15:41:24Z"
    mac: ENC[AES256_GCM,data:ZAbmFUzzLhnTidB4dpEerhfNMBn8plv0mE7HGS+pGeYW8gFda0eFcJG5S+325yh2BZYZBYeRKt+VtsKFgvXhh6bRcSNW8ew2G/N8kqSAO1Sa/omxD7XbKIWA9EZVcVtRJ7BRQqVZ2DS/R5/O09kZpwhHOsZ022Xj0Q24tNSF8is=,iv:xiXCl7GGWajBcW8Qk5OUFSVuzmj4DweOajlLD6IQucE=,tag:N5t/n6QDiFXpmyJRjXKKrA==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
