apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:IqCo0CjY2hx/Cey1I+4OlWhRrPIwYufdV94iWRankvHhy797lA==,iv:dOv6cUXT6jmcxMSXUFGSbuJilVvbGDpwrEuL332OeH8=,tag:ru9mRlki4zmk9Jb5K8tjIQ==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBoVHF1U083QTM0WmRpWVZB
        NHAzS01wTGFQR3U5UmtjRWpQNWhOK2trQ3lZCnFvN0p0Qm9CQmVBUXMwNGRlME9B
        U0daT0owZWJ5UWlZTWYwb0FlN2lXMWsKLS0tIHJsODdKWk1PZ0VTaW1PaUVKZjJp
        UEp5NFpOd2o5ZVZlL080dlFpQVVZZVEKRGrG0wPwcixAGEK62U8HezaVfkDFQnya
        YRbtK8fMp4ndRbgLfKAFpSu0UdQzU7CpivHi+O4/8cRBjakLXjsVAw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:09:59Z"
  mac: ENC[AES256_GCM,data:i2LbLBOhlTEKI0tuML1zmwma+Qk1H9qT893ouiMbB3z8AdMgRZ0xx3ZPoW6G5ABGZkV1MytkASYG9m7OOBMKwQwsELAkur1epxpk5PpPc69luB4ZVJ7WvQJ/MsmemB96SirXNKPXQI0g5qoao6/8WgRuqZd9w0NfVZnBe9ACNuc=,iv:op/2/i4bMyiTONhCT/ixx8VuwWKZY66uAaumHgnsWGU=,tag:4HgdfPMcO13SqWWKV80Huw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
