apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:cH8f/mOC187nwDai5E0YpNGUVtruAP0AKcDEYmsG8BM1ekc4Kda1TA==,iv:J/uvJjFuITmr2Jwx6tZCJhtdOsZaiie2mc++Tnv57wg=,tag:DV3gsl6Isp4C+kbueNDkMA==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA1dEkrWUZBQ0Q0ZEczOGhj
        Yk5qNmNNb2ZtSFJNYUFPd053YVQvVW9NS2trCjNYb2h3K2h2YnZESXdRRXh1RG1V
        OE9xcFBCeDlYQnJXNkszQUFSRjMyZ1EKLS0tIEozRkd0cTduOW0vV2xjeXJLbTk3
        UXRhOEZPVkJOYWJJN1g1SGJHTXFxdUEKEoDkpg0ga+pPhHdL/v/vCowvW3+HKHds
        JVg05OD45H4LczLHGADjnsxc+8ccgBK9VRIZTPz2cy2xF+CiowwOqQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:12Z"
  mac: ENC[AES256_GCM,data:LND9EVUsINDJ1mjW39je/VL7pjtYhqO3GyqbAUfefh10dCPlGKQN9nAG6kxNjGtpxfpUZT105gCWfnIfLvt7ZInDxiY2AumTEcP+s8VftGqJjx+avwZ1LYzXdxGpv+fqjzZpmnI9SM5P5CfsbUtAiq0Xva6fglq4+e4fakZiyVo=,iv:wT+pcHE9Cs9D8NN7ypaQs/ZR32QZIbA7K6UFdR4kuoA=,tag:rYDjZCQXGT8c8kyGQj2gQg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
