apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-dns-secret
stringData:
  api-token: ENC[AES256_GCM,data:SMDwtbApRbmloY9/54Rm0dv7EtMVx6i6sYe/3cBpUAVDEivJdQ==,iv:cipleec06akOmYogMHAsshi7NfaQiHXm0FFm/RjUNzE=,tag:kn+24Xy0fR1df791kJRW4Q==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSAzYU5oaHFRMHdQVHpYT0I2
        ZU95SUEzVXZxLy9WUmorb2RBRzJiZ0NEVWxJCkpIamUzY01KVCtzS1loNlVVSGNO
        K1lLSmpxNG9rVGtLdHpTb1FPZkN4OUEKLS0tIHQvWFZhakplb21EL28wcEVQQnlS
        SXpFTG9WVE5adUkrNHFOdGNFTWZuRFkKy3MpZLkNBvN0ORWrRNtc/grQUN972fui
        pigEDVxF6MUdyCCADBbUba5es1jPZfdDicqnmiUkyW9i2pJEAUZwrA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:56:44Z"
  mac: ENC[AES256_GCM,data:N7wxjTM3Yf/MY3NaY0YAsNMMLJ6JuKfA1T2M6w436mpASc6FtR1zqu0UNSxt8oVaMpJgynBQXfynKpLxZYwpKmRizRIIgshxljJWVAem8nkd3M3UngIYJzKximv+XyHcs4DHDVooCb8vV6+EkLYt/ujKHjXiW+9LY22OOL+afuI=,iv:9OSUrOn69TSBaT2Z4cJxWb7ka6vGtS0ylAgN384faIs=,tag:mJPaUpEHa6k5Tu3bxn1QAA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
