apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-dns-secret
stringData:
    api-token: ENC[AES256_GCM,data:pTjisvYZg1dY1FMDbqieFUzN/F4QOixT8mWwSsztoz2eQwARHQdMJA==,iv:TKN/diH028m19aXBfWts2tWWIOiJdk/NOGki/ET+W/w=,tag:ANgBToW6eus8lVnZbiHtPg==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUZXluNGl1dmpNZTFGZENo
            Q2VuaFArRHJmUmFqeXdpM0ZaZDNsRzI3cTNNCmgyNE1kS1pnS3hETmQyZERLNE1Z
            TEZGL00yUUxscnFyeFFpaG9ZSzBDVmcKLS0tIFFRVFMxNGFNSityMjI2N1ljUGY2
            ZGR1TjNHNmlpSTdWd2ZLakVJODYyYzQKlp09zuQ0zHlmVjJVpksiyHrR5xDYlH/y
            kqKkyAq8ZMHmqF0c1hcoApx83EgRK7+yCwzqLsKNrf8hRiLhGq/gZQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T11:47:09Z"
    mac: ENC[AES256_GCM,data:MQSvyw6uOIAxn34W16TFg6aUyxWi3O+PDyB749IHL6ypxNeSkr/yhr7qHZup9Jbi7VJO15zE7X62IY6WxZoc6tEpuQyb17vunLgLEwhY6qyfrU1VrkRrEqtWNn1L1wa9jFT4FoD9UhJJ6oqMOvLbgpnzzWx4Aoztfy39t29uDF4=,iv:Emy2/ZjrzoMY9gTHS8AE0dTzncVKFMLmO3Q30asy1y8=,tag:weSAAAxirxLVlWRS0m0f7g==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
