apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:00JUw8i6ieDB9Y4=,iv:DOJYN2au7513apKi3jvBdNuAdKBCmkYmAL0OslFBIAQ=,tag:vjbjXlQziE1VQFcH1AMzgA==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB4VTJoSytISldTOFIrcGp3
        aW1IVFlYQVlsV0N6T0J6eXBnNEEzRlRCbHlvCnEyTUNCb3FyZExBWG5DS2h6MGt0
        UGNPaTdiM0NXZUZzbGxoRDVnaXpHYmcKLS0tIEhwL3B2cDkvSXZaS1ZCVG11cjVY
        TDNvRjdVbXYzTFlqRkRFVktHYlZuZ1kKSb6Sm7tsFQvJRGVfilbQvNDPQyEf0CLH
        WA0OPYHKZ9yZG85CzTtXs3SWDwng3+3XLhtwWAi0Gx0ayFatvYkvNA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:56:44Z"
  mac: ENC[AES256_GCM,data:svT65N640KkEhudmaOK19+sP+z+2c/5W16ocSY0sEKCLhEXCYuMzXsF5fB5YYufeerNNdPBIo5a/+KXE8ZpIeXPB7cyWulNv26o0zMsxjQhAfPPEVIoG+lYgw7s08vyULe4fvPd0TVamU5dRuTnV4Kz7aRfSLDH+vThXlfLu5f4=,iv:pDScmXTlCRG7Nj6Xoa7TYXuFXVAL9R/hjljFJy4uZYQ=,tag:nTsaNcb6RkkJZ38gGIVlHA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
