apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:kadfPvwsGAdI1RA=,iv:UMISlCuDCa4hddMJPzT3MH3EtKN0wqaLFN9aNEWGwoM=,tag:m66niZ/hq7SEnhfY6/Fvgg==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBKaDQvOXcvNjIvTmI5UlZQ
        ek90a0NhRXRkNi9GdkpuYlNmN3picGtMODNVCkgwbjlZRHNXbnVRTm13UmUzQWZi
        QkpuRzVaaHlQUFNLcFV2eGFqdzNJVWMKLS0tIFFSdWFpSUVSbWJjNUdiRTNMOEJO
        eGcrMlBHWDVuYUJsMzhwSXZyQXRTRGMKAAw2Fedoxsmi7uou7fc/h2KW+eY202y/
        Fyv4NCxT4apJctysstokgM5o6f/epCcCl6jyxw9AvpiZfLR5KLd1kQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:09:59Z"
  mac: ENC[AES256_GCM,data:Bzs++QrbdL+fMx12pCVKRrihQcjBWBv7tdELC+I9iMgghq/6eptX7WzuCVDOJVy1hB17xeIJq1kinEsBwCi0c8zrRyrLEGEbMX65hyxkzDtHrSH04MmSQdPMlGEdK0eZ0++wB/XLZ8Pzg8dfOCv+CBjDXaapLV9IiJ9xkLjLEqY=,iv:MwHV4ePzD9mbsuoke3HtZvyPWl4NC0yf+aAUi96gFyE=,tag:OotNby2KuKGWIu9N6molRg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
