apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:dk5D69CqRGVjRZI=,iv:dXPpbbGbwHGESE/j39T0Wl5+lRYIRVgbuTluSdRAXX0=,tag:S/G4CiBKPn4xQKmy3av+3w==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3TVNJVncrUzBLeXRkMWpr
        Wm5vUFBWZHpidnpHRktLbC9sVmNYYkhCOEhFCko3MHRNL09rOXBFTS9ad0Z1SDg4
        VXdGbnNaQlh1VGNNR1BNTVV0Ukw2cHcKLS0tIHNaN2FTeG1uTnpkMXNpZGpqNW5x
        cnZYS3hyL1puaGlMVXBQV1FPNk1WYWMKrHk/4F0jqlpi2SL+2/vXPssbEJkjV+gb
        4kdaCPPiKr1pufEoF2w5JksUwiAfbmIXIhl/K1ennSaX15PtPu0sTQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:19:03Z"
  mac: ENC[AES256_GCM,data:bW5giZLLKwqlU3bC1sMb1dNgte3IkggLSeyMhPw8XAU55NpF8e/5GGLHJ8q/DVypTDCV7GWEYUSvLdKA5v/7Ye8qlfpqdbrYNI4o2cRqk+FotKjJmxGdc3npJlsHnN4ZYOc2qFmVcW7TTg4TfFGA1ILm4+C6EFCAvZzyAm2krFQ=,iv:aSpdhi8slZmSCSOqZSgP3PlBF6u/YIm1k7kwIZ2MZms=,tag:TveAWXZQ2s6jqlL+sfzYuw==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
