apiVersion: v1
kind: Secret
metadata:
  name: cluster-secrets
stringData:
  SECRET_DOMAIN: ENC[AES256_GCM,data:Q1CspdtJnnAH3oU=,iv:xTfGB9SMM9ghMdPztiAKAkXe/hBmxqCmBDPXKrcPLBI=,tag:s7Uej/izosY6gZMOCV7mjQ==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBUMjNQWnVJVUJqYVhKbVpE
        bXdqdFkyeFZNV0pqcTdEb1Y2WE90UW5xOWlBCi9vM1o4VG1WSjY3VDkwMWdGOXNR
        a3dUQytyR2w3QVJCQSszazU1RjRtZncKLS0tIEJRbkliWWpEemhreEQ2TXJPbzh3
        OE93MmJ1ODhWYk5FSS81enlLdkp5SFkKkgTGOLjH5n3SYu+/jRrERa0tbOkIYAGe
        GkooPGV8OZlJrW1MvtMftlMgmaVt8Bth/ejOcLIA1hcX5MyFVB4eKg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:12Z"
  mac: ENC[AES256_GCM,data:0gZt6kOsGQtLsB2LSXpdB/Ifkoq6Yu6YChwfJJAj2q6qwt/iBDa4+fff93nDfzOvHW+BuKeqkPiRx4bKfsv97nx+JOvDi/YWyYb3+lwuUwv82bLaeToI+lJCCfYQ8enQbkLGNoFGKiq+m99f6GR+8qimB3jYe1e40Bjqj9bguMI=,iv:FEDJg53Mi1IPgN0mfAaPZAJgKgXahtBCcU7MyGYb+0w=,tag:hdptAei4BEvAq+wBE4VJUA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
