apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:wtkDsDp+Ex71cSho+h92HQW76CGHjC/jGZ3YVYLNIjw=,iv:UwvBED6KxHdhJf6l393ly+nTsCgiTV+EMIeJdxkvxhI=,tag:XEyTBg0Ulul8eVsMIvaEsw==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA3NVNXdnVkdWVYUFZla0xU
        Y1EvVWpENnNBNkJKTU11djBmemZQM29vWWswCkhxU2ZYUnY4K05CWGhrdlhjN3BG
        cE1MTWwxQ0ZMVklqT0F4ZDFsbUE0ZUkKLS0tIGpKQWZVem5EbmtyM3d5UDRaMENO
        QkVqcnMzWVpyKyt2SHBBTStHb2pQRTQKuu7iTBgiFZ+LDqGhW1CAJhKF0Dfy9BJW
        UIrTZp1lbMqybLrO0ZwRWJobXp1fjhtGKx4dGLbWdcVdq6zbQawjhQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:56:43Z"
  mac: ENC[AES256_GCM,data:teWITZ8U4FBlgHIRb532cYVw+bHvekXNAnpj/Y7rZ4wTx9zdqnnrMMHzHeXhW/9vbVi5M2cBzxPKHbhe6B1bsvkrIS4pm2QJ25CHGRO/euAbly11xJJlV+Gmbnlpw+MibiqvcbkhzGnneOJY1nagebF14zlcvrE1dzDrtkG7ks8=,iv:vBIuYyYztan58LBm0m5AwoHcnJPdt3GUkxxuZf8Cb6A=,tag:RH+aD7EQIBaKLbTcdhqqAg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
