apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:x1wN4zOx/S1j+J7CbY49naPZdTrkwT8Lan21qBvTNdg=,iv:zZ61D0DF04NSBP1NpiKSdKvcO94sbxBbzRT1O7Xay9E=,tag:xGGTYJCCisFx4u3DRDp7jw==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3K25QTWdXTHN3NmlvMmQw
        Yk9GV0tsTW9xaXFLR0RqaENTSXV1MEE0QURZCkFLS3REZjFLUUxPZFJieS9ZTnpU
        M1k2RmJ4U251aFNCNi9uZ2dzK2twMEkKLS0tIFpiVFBzQWkyZ3VaRTlneTgyL1lr
        UXRBNXN6YnptNVh2ZkpUOUNvUEtkaWcKlF+ndbJdPMrjdOhxUiFsn3nua1JtpG8y
        JlAn5paUNOMIeVzbSWoNCv0+yxN7gEj8Tbk4pQy8vQMb5k0Q5nOrdg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:12Z"
  mac: ENC[AES256_GCM,data:L/qsKO0/FdfqYyHcQH5cJHVZbFPdFW7UxauY6VV/GZLMx9w+v5CIN/W6nqoVY9gQjQwxNRKEYnj+QyEzNK8zLTmsE8iOL+uvnB7GrXzNXkyQNl5fcbvmZ0pqo7CAg1HzdDzxh+88seMHOmzohW5vHjYj+o3XK8llMjHAbg3bbZ8=,iv:LQ5XW1YdT959mcW6lnKNZ4QsCqyawkf9cOcFJzYI0pA=,tag:rDct0Zixn8rmi6wL4yYVcQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
