apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:ZcscVvzLXATkdjwdaFfaqwGvHZeZfzIoaMER/PzrN6g=,iv:SdTcFDjTDkvJCZY4CgEAyP2i+AaBDoLOrKOtTCLz+6Y=,tag:PFt7sX9QLzbhjcIoL//fzg==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBIVWNXRllaSTZ4Q2srSngx
        REZEbkdoYVJaT1JZUmFqem13cFA3blB0N0MwCnFLVW1rOFhvME12NTF1d3cvN0Fu
        Tyt5UFFDZTBqMUU1YkNKc2hPV1RoSjgKLS0tIGtKVDFOcUxOQ3ZJREVtSk5jRXU1
        djFvejMyVGJhQmwySjNNcWhidVI3VG8KLbn/Zpf/ZQ72YX5MiHHohj/TEr0xYkZb
        0Wqp7Gozj8dnpJ8yUXTz2DaDOvp+q/DdXFJK6jAHnfPUonBVC6PWWg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:09:59Z"
  mac: ENC[AES256_GCM,data:/bzxA8WCmpBau0J4fU5pi8S1rV6P9WRAg1TnPmKSaCTYYpWLChFk9/H3bYtFAf0MFZ12B6AUBVjlvstGiozmTEtXSfMwYH2PCep7HGRLpYcQuHrA6yLsh9jqGT5lX+6zPVDfqvJpIQmDTNPxTIZPRUF9oi5RE8+mEpMrB7zPVec=,iv:NeiEpmgEyss7nhpiBEpEUBzMB1dFkTS121GKeu7cvJ0=,tag:enrsp2GDizjTai0gyTdBfQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
