apiVersion: v1
kind: Secret
metadata:
  name: github-webhook-token-secret
stringData:
  token: ENC[AES256_GCM,data:AhwKqpJtxRdj10jZjwrGGeeVp8K4RPVpwcecI8EUdas=,iv:d4H26ZM9h6Y1pPt2j8UfQKmuQYmKxxKQ+LjHLG+8DkQ=,tag:rop6mXxlGJb6i+bJPHPMZg==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBGNUZHSllEcnNTU01MYWlv
        SFVlaU9QdkFTWTlFVTNvS0hQUjlSSzRaRlg4Cjg3cE1sRk0vTlFQYWlDOVg2eDQ3
        VDRjeDlGRVNqNXhMUjcrWnoyR3RHVDAKLS0tIHU4bDM3RkUyL0tmQkcyeDAvWkQ5
        ZTdhc2tCQkZCaDBPT1haRURSakpPUTgKfBdwE6EEigIYFcIzPgAyrbRkwHzNaQJn
        Ap1gEUIXTYrmwkvhNR4tkiLNzBrU1qaEQQaujeieDRCslGRGVCGBAQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:19:02Z"
  mac: ENC[AES256_GCM,data:hErWJin3/cSrr9M4r/a/mRadHYwgTPbBoa2ELjia7QtYqbiP66oiel88mVCMVkD70qBXb6Pb+wmLZRrgghYpIccFVu+H2Mhvxfkkdq9jH0SgYg9MXBF9JsCgkBYFA/UFD67REmAW8HOrBsEtqv0HlA7IO0rumx7Wli5tbanJJPk=,iv:3Etc+vWaJMYXer1tKUvoitjpq3H31buV6tSBAK8aOGA=,tag:CdWsjpgYClLCq6jRfgZ3BA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
