apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:LJf+tgmmdMxCLy5ZwC76tlHzlZ5GHb8rI51bXCn0dbs6cqZiZKIykwiIkKnZPMLg1fT6juDg/lNHxGzrIFlhDi6VMwZCrSRPYhLiLMwocZaD1i1HMlGR2OCpFZ/UejV2aZVnVrhCvGpv0tDB1sPbT8PuYHtlxHa+PrXYXfJraDjjMVYG62koQt9Rur9WIzlNWpOY4CCgQ7I/OjKSUqO0rzM68a3qJn+xbKetcJWboq03TPvq,iv:qEX7sF1EJQi0wpD9OiBcymD8Cv6ZSNTnNv3Xkl9vd8Y=,tag:bFox8Ow5mrtetst5qsnPSw==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b3NHNHpRTHExOW0zTEdv
        dVpScG1TbkJPUFA3cHM0RVZjM2luS0ErLzJnClk1UFpBZTBDZkNkM1V3bU8zTlBO
        OEdxNHBpT1hMYWxiVk9laTlOTTRUQ0kKLS0tIEtRWnA3TWIzejFYY3hLYVhuSVNl
        Q3JIZXZxVTRBWDNsWERtaWtkbkZ6QzgKrDaS8ko8o2oabyyCnZOATQpUox1aiSiJ
        GGGsiiyfKsv6z7ysXZHE5ytXVV22ehaHrBrZbep1SQ/mHludWCguHA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:12Z"
  mac: ENC[AES256_GCM,data:RSadglXdumi00S9mP5IpFd/GpvhVPdN2bRdACbj9blHINyaRYVX7eepJC9cnKeI9YF938YXvAUZOSLgu+T3i+zJ8ywSYrAxtxg5Mi77ElobypeIe+E8Ks+dxw7ldqWr7864I1fMpM3fAqIZHi9wrybg+zeQFd/p4t7cHo5/FqbQ=,iv:e5wttDreVVkCnHrrrm1E4wXf/JiePXRYo/mk2RE/M64=,tag:tsWU/9RZiyFtyuAKBugRig==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
