apiVersion: v1
kind: Secret
metadata:
    name: cloudflare-tunnel-secret
stringData:
    TUNNEL_TOKEN: ENC[AES256_GCM,data:vHlGsbHUyorc0v7hHamMbgHHjXApg5KL4VKzL7GBjYFCNsQ+PCkDkZ2oh9i2G7Be1bu5sDbLwAQ96ND/R5mUcRcUA1ah6PYrfnoXrk8yB/s0VmxcTdk+F+SO05KW0w79UqSyZxUAtE+rr2dZD4gWOZ27BjpDUkmEN54D7JXMSLvI0G3QIZ/F4+e+dUTEUGuvWvIvWOrFE9ac4zuCGESZaCXxOEPH9/+rjX2+orHnhnnZ+bk8,iv:kALaifvkw+jM7X15ZG8vCveqaNqaTQdDqxTiwlFMFN0=,tag:rpkbOKVIk037YtLjvpJluA==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1JCWkdKa1BEdC8wNW85
            cmhkWFRzSzhacitYbVE1RG9WSm9UbnE2YWd3CmhUNWdNTVVkbmlNNGxzMjJrT085
            THRPL0x0TXdCVHZqOS9OM3p3VHJlOWsKLS0tIGNkUDdXdjZGMjFLUW9pMXpaamFB
            dXR2d25pWWo5YkRqMVlGdUVRcXB2dEkK1adPLWsYI+ZNzPqdcDRJYZ+NumNbxULe
            sl8mn3HfS4fFWCrQ+37oF3X3tjq24A0Y88sLYRI5dMtqjL33LHvOKQ==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T11:44:58Z"
    mac: ENC[AES256_GCM,data:fKGKELQ8Zz8OvHX3+xTptJ7kQNm8tzf61RJG72UgVt8P/gAgg7DI3PhPYvf2zIEgsxp1jRgN9rjjS9kcsqi0D87tq+mn2KegQMf+ksSvAXjxJdJ96hWB8Equ6wddPDEqiIKoo1PUwmfyfVDRahKHPJDJJbJSJNGuWZvWeuEeIKA=,iv:fOFIrMx5mb4/xu+PzJUzvKYH+er1/Xa7a5tbwu9pdVk=,tag:aXT6RiF8IBh+kxsAs+G3Og==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
