apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:cWMOYKZxuVSVhYgU55POt+TvfoHCZQpyIMq77rxJ70OVpb41b1rLGARDlmWO1zRvzwE2zQo2/Ua4TC6pi5hxIS7QeLR+XvRzOLh/vlDFYbbnsbGT4QG7WCw6IPAwRJ+w8JGtHTWd3Xb0LFNoFHHWUZ46vj9lRA2bO+9cPn0Xg+5R7XeGGei2v1xp9aMlSHTt7TPEyb/7co+LVrQflVx1H9HNDhuQa+lkhWzXIfiXSvKWrSqi,iv:guBCoGi/6KpQSeQEXNoO9C4UY22n2h4iS/f6THmG6u8=,tag:xVZuGQnm1YCvrpGSVGTGNw==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBFU1JCWkdKa1BEdC8wNW85
        cmhkWFRzSzhacitYbVE1RG9WSm9UbnE2YWd3CmhUNWdNTVVkbmlNNGxzMjJrT085
        THRPL0x0TXdCVHZqOS9OM3p3VHJlOWsKLS0tIGNkUDdXdjZGMjFLUW9pMXpaamFB
        dXR2d25pWWo5YkRqMVlGdUVRcXB2dEkK1adPLWsYI+ZNzPqdcDRJYZ+NumNbxULe
        sl8mn3HfS4fFWCrQ+37oF3X3tjq24A0Y88sLYRI5dMtqjL33LHvOKQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:19:02Z"
  mac: ENC[AES256_GCM,data:zF0EY7roiKgBjsO8daTFod56Wvs3EyZ7Xykg+6WmQKWnZHhEmckEH6soqsUmrLNrnv89ZgrSh6BJujCGEOfkweDsmUR2Diz7/ewmpUiEOcrMLtSs03oZOT68z95cGvSoSu1+HMs7YO8NAJeHvWl1BqxmTqCZe1NDB8ant39AJYc=,iv:U7lXsRSedJ77ErpeSkNy4p4Ka0YSCeU2NL5nuBpUClM=,tag:iHr7BDPt0VzlxP/mxEZzcA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
