apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:zIbirBOWv/ISz72Lt+mD8QM7pBZw6FB7tVtilieVrbPb9GypK/Nm4It0ze/uR6qy7puTDS1tDjHJXGF8I2IUlo67/7hxv+kSWTQ7c57cnJFIbyImJezyzfLpJdn7HSFvZvrNLnKrYiLU7u2fHmmh6ztmVQzhZ89rC4WmoneFoKi5L4vgtK9p47kewW3cTUuilp+e2J05W8yJTnWMF9luIMhM0AHu0e+QnoVwIZEB7fbDbnZc,iv:AC+aYsMA1L0fGjPFeWRVBpOozXPrxGDIDYJ8x/IEVTM=,tag:fRvixXPGEcqCMw2tc/6QCA==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBZTFBEUXlrV3RRZHA1eWU0
        SzJpajJtTllQeTJHNENQN1dwSXhEL3NiM2dNCi9rWGQ5eE55U1lDOFRwRE5OblRX
        NTErczBkMEtaZnVSaXNsaWF1QTlZaTQKLS0tIEc0YW5ybUl1UVpERGVaaEpLdnBa
        ZFphM1NHRk1ONnA0azIwVGg3SUp1MkEKhjiuwIlGaV2iVHG8vR7mZmpUSKk/0tze
        W7B7kSPfZQvq/Ezmv8bwcATZK0mfVlAOoScmeRQQv3VsgIRJt3BrtQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:09:59Z"
  mac: ENC[AES256_GCM,data:BN2EH21Dr/WQGaI+QLada4dmzPbcMCJ2/ILMwA45PF8enypv3CmrI9k/CLTHBYEOaFb+m1KirWccG4tSNF1prlEmcl9fooULEM34jhAre6sRrWgYLOPa4GNnrzsBKR95jjjnOe14LsM41j56iwJj0getZSkcjmHclv8Dm7L4Wa0=,iv:0By6ndku0T2VgzM46sHmq7OkTzkcorlvQMckUJVLPS0=,tag:zCApyDFU6loXzjhbDnw7YA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
