apiVersion: v1
kind: Secret
metadata:
  name: cloudflare-tunnel-secret
stringData:
  TUNNEL_TOKEN: ENC[AES256_GCM,data:rifcZdyGBqvuSQJGKd9fGDuFwob5Si5skm2C23W6iG81vQQMqtXoYyc90PbKDWJccsBVuQuuMWf6w+AS5k0cwWr9lFyoOYHTYKUqLwFia6YLkEEgtnuCKSMZefCLsfL4Kf1C+nzNUwSL806TPlWXPLw96C/IOKzVpTsbp7BLhOHg6R+vKfuV0T2qetGRTD2VkzuFI7a6wqOiu4Li4FbbGfi2qxNvIYE88oYetgGnJVCXdVbD,iv:h+kbB947mByZC6UW8oEBABaVWlM3zHh9F2GX3UAkifU=,tag:VYjtGj3KeHHIepbP+0sJgQ==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBqMDJQQ08vc0NFTlhTbHp6
        elFRV0RxNVEvdnMvZXp0MlRzRnlQUHBPY1hzClZqbzVDNTdTSmtNTGQ1UUdjZVBF
        RVphV1JBWWdiUkNyL1FDV2lnR0duak0KLS0tIFh6Q0owM1hWSFdpS2RtaWZtbE5O
        ZkYxVy9lYVI1czkwUGs2eGpXcFBidGsKUO5fzoRKv9ceByWObs9i4wJNsGpUMR07
        3RQc0QEwjDK6uDbwuXKB5q1U0dn4/eLWyOYhuycxuk8nTRWkIr9viQ==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:56:44Z"
  mac: ENC[AES256_GCM,data:D3pexcm9QkEbzfgLF2rQzCQyVHmNx0i8PIxmnR6fGfolFjlNEkWiKGEhixgC7LKjbfNnawsQnCfrkque8G/S5QrjzmCX6I+1CAzCiTz+fRpFSBN5HW2cUY3o15BAA5Fro4jCLLIL//rLyU033b20o4c8Up4xkhzvDBUDOGRz+/0=,iv:A40RZ+EHkqWmXzRxDWlDEAK/zxWUq281886RZQ5jc/w=,tag:1c46Oi+Kw3uIBZqhuf8UaA==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
