apiVersion: v1
kind: Secret
metadata:
    name: cert-manager-secret
stringData:
    api-token: ENC[AES256_GCM,data:yh1hRgr6xcZwCySkmJI6TGwL7yWJdqeUrh8df5VGvUxtgKsVFWZTCg==,iv:YciYR0sVLdnz4DnjmeY/LTeNx4bvVfyhy+jc42loj5A=,tag:aPRSA0xkXULyAZ15xq1vYg==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXBDR1N6a0Q5U2x6UHVU
            cTdUa3Y3OWxGVlF2MUkxeWdhWWhOTVh6cmtRClpBM003WTd4SHVRRFZlS1lPcjF0
            R2MzZWdYRHdGbmREbkdRNlQ4NjRQRmcKLS0tIGhtRWdKVWpLZHJQbWloeG1UcjJ6
            ZFoxU1pvek50MU0yZUhHaGRMRUhFaWMKF5HODFwp4UFIY4ORhkJNhKTV5pKMarWf
            E5ytXRRIDHivBhTn0OjwfF3tWqNWYuBXbQiUsyWLBNzxRGBwwchanA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-30T12:07:23Z"
    mac: ENC[AES256_GCM,data:d1pV/I3BX8XOk68TjuiBNRsF/xXx4hkwwgnxh9IDhwweG1YcGjf5rTdBkgoxunpYW8BsYH4XwJa9oxbEe7O/zSE88EmocQ/S7BVNU9df56C22oyvxnYDqnB58cVY1AzrbI1fCgcF81DJazg8K94IHiM6Jfxma8bR3yY/Zs8P6f8=,iv:NSutKNBPUZij2Hzph9TWWnbdsdSPxng+EBeONmdvfiw=,tag:LPhxIRBRzzW5JnneUqvt1w==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
