apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:y5JtL1mmfCLFSTyMmpAnBk6N7yFSFsQa3FrTH1Gr0bmVPBU4Rg==,iv:8G72S7nKbfJfytsWTKIOH8TK/sGTmvfkJvbkEgYTAhI=,tag:pfGTS/ZuusRCL6D8u/y3ig==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBXOXBDR1N6a0Q5U2x6UHVU
        cTdUa3Y3OWxGVlF2MUkxeWdhWWhOTVh6cmtRClpBM003WTd4SHVRRFZlS1lPcjF0
        R2MzZWdYRHdGbmREbkdRNlQ4NjRQRmcKLS0tIGhtRWdKVWpLZHJQbWloeG1UcjJ6
        ZFoxU1pvek50MU0yZUhHaGRMRUhFaWMKF5HODFwp4UFIY4ORhkJNhKTV5pKMarWf
        E5ytXRRIDHivBhTn0OjwfF3tWqNWYuBXbQiUsyWLBNzxRGBwwchanA==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T11:56:43Z"
  mac: ENC[AES256_GCM,data:Il/ijMhPBRyK8xGV/9XyFM4tga1JyBZIMMAzznvaaTleZAMJmCDnabIjxtlv4rLwXkP7adZpV9PbKKDJIfBtHYA4ldQ6KIXCe1KSbQE6tTjwd983feQmkQRwyuXzxXOq5mAZHP2QqyBoTMhx/MH9pfZ1W0Kjm7/8PbgHhEGzqj8=,iv:FJZTLRdSRkrO8/MZRGdktuuT4eC+pQJh1o831vnWWjw=,tag:nfCn5h1F0Fu2T0YrUGqjpg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
