apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:yliRvqVNOK418Qlnspb38uxKNbAHhHLxQo/0jdaMMhgy+sw1SQ==,iv:Ehy6KuxC+zxxv+HB2EEd7btfUydMwLhXeZYvJreQbZk=,tag:ujffJVMZoR+eqtG2p0VSHg==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBxeUlGVkMrODlBRExUVmho
        eHZrZzNIdFE0ZGpjelFEN1YzNkZsSHB5aVFFCmNzbGNzTXcxVmFnb0FKWDJiam9j
        OWs4TEZZMEVuRmJYUWtlWUR0eWxFOHMKLS0tIFRPNVcyNXExQTVyY2U4cnNDV284
        VkxwNWh3VFFVMGMrdjVCbGZMemtPQk0KODtFzSxFXk4xUx3emctzmlPnUWpP/nK/
        FrpPd+xGF7j4JqVlOUADTTgSZIvGWSAQxg7RA34rj+puOrDH2FnQQg==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:19:02Z"
  mac: ENC[AES256_GCM,data:aBDagPEMkT2a7C7r8xLpSQAvdDI+ZJLGfcg3tU9BF811cFTedwklc9gBfi9v2HnYrVSzxGbt26CB0CA257QYyWHztVAEuwTTs7nZ9j2SYSMhCRNkJBeii/EQDrJI61e5LF9VVxDgkNISxHUqzLbjaVOa1ZNgjlG2TVRplhe6ImA=,iv:k5sWbQiYxAuFoGhmBeLsNcXecGeJ9+9x1XRiFF9lcZU=,tag:cSnEChpRDGX626pzlmHFVg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
