apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:JeV3zHJ0bAmXFBjfyhfCK8HGwTvXNAEm0LcXAJPgzkmrPqG1X3XDTg==,iv:L+5bECjPBOaYxv3dmOjmFH4vNieeW+IMcST3lo6ZzUY=,tag:1R5cAQFg2ByeM4I+DgYV3w==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSB3VGNQRnpjM2t4SmZzWmcr
        cjBSaUo4d05qcEtCSkVuMEhHb3d6NkE0cDJjCm5leXNDYjVWQVZPMzdwMDZicjVL
        SFlZTXhoenpEK3JBNldHMlFtblQxSzQKLS0tIFBrWFNWUVRTUWVZN2hRL1hVRjdB
        UFdNWXhKTkUzd2FQcFFBVXc3dVhnUHcKDM3g87HZbHN6aYEFupwSOqkQjUieKCDr
        D0CEooMb8Z2oGLSHtWBwxevF20Eb69renilVTSwvdglw3Yoihi1A7w==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-30T15:09:12Z"
  mac: ENC[AES256_GCM,data:saofBWqy0Pcn91cvSyvRzMf2iKXYJnqpPvBBqSDtyWt5OTFN468n62QThwQQZunzEfN/BeUUTaBjTu7ZYCKcnhTawlMB4/2CiwtEUYcb1Rq4JPafWp1ABETvBsraEOWk9kioZpxZ+LeUxylf7rEPuIgf1B8Gj1tU6l0GTPmjfRQ=,iv:fXIWUR0NNfTcMTH6t7cj/L7XVVeNJUoIIOe9Nq2pgXY=,tag:+yy5mnqWibflBLDrZTTeIg==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
