apiVersion: v1
kind: Secret
metadata:
  name: cert-manager-secret
stringData:
  api-token: ENC[AES256_GCM,data:uGDrVhp00Kok/wGgGDhzl5ZIPSEjXx2DpIyOzZ9cBtj/gF2IaA==,iv:It2Sh2sCDc/UJV7cQLx7jjZXeoeu2k5X83AlHNmsn/0=,tag:RHcOUXxwmZ2VCb/zTIcXSg==,type:str]
sops:
  age:
    - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
      enc: |
        -----BEGIN AGE ENCRYPTED FILE-----
        YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSBVWndoejNjQm8xNUkrY3Nl
        VkR1N0VyK2Q1ciswMnlUQzQ1WDc0bUhpdEh3CnBFK0FuejFnMUJEdTQrR2tFckx5
        U3hkYnNzOU55akppYjFEZWdCckxuL1kKLS0tIEZ1dVNFcGJ5d1dRS01CQnZUS3FD
        bkVvOEQ3a1JqYldFcUdYcWVRWExHZkUKGLOKGdPbP9I8+uXYSIknAWVHMG5q9XlF
        kf3XhRY5o3Ygevertx0NxjX6uVqzBJ59Reeuul8lsc3e07vghuaaaw==
        -----END AGE ENCRYPTED FILE-----
  lastmodified: "2025-12-23T15:09:59Z"
  mac: ENC[AES256_GCM,data:bFqr5FyJzmUSM1d8AZWm58/94cqSwV8SD8N2c6NwU/CUTSHWZcBlqFUNTyQLlln+NTYWL2+9De4iprRuL23qTl/e5+YmOLwCpzvKoQOOc9q860QYfw+xjoFdX/KSQugt+MB66waEGwkSnCfjRrMmFXjkJncEzZHnJ6lqddSKiLA=,iv:kPxSeDIRrN0nNvJBDyXH9GL4Hr0C8MsIkvBr68NWjsQ=,tag:t9OJ60KzyiG7L3V9f3dCiQ==,type:str]
  encrypted_regex: ^(data|stringData)$
  mac_only_encrypted: true
  version: 3.11.0
