---
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: "${SECRET_DOMAIN/./-}-production"
spec:
  dnsNames: ["${SECRET_DOMAIN}", "*.${SECRET_DOMAIN}"]
  duration: 160h
  issuerRef:
    kind: ClusterIssuer
    name: letsencrypt-production
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  secretName: "${SECRET_DOMAIN/./-}-production-tls"
  usages:
    - digital signature
