apiVersion: v1
kind: Secret
metadata:
    name: externaldns-unifi-secret
stringData:
    external_dns_api_key: ENC[AES256_GCM,data:vogsdfFOEhnxbOJLtBgph96CExM6ut05dSwOoipJocg=,iv:TaUMt0sQaC2A2mYflzntQgsjmcbb0sLgY9ZWAovRKWY=,tag:kXdu08pP6UQnPjhte2S/lQ==,type:str]
sops:
    age:
        - recipient: age1920a0lamyngzs5xszlmhh6e9s5gk9hqnahz5k0jwednn4jffkyvs0puxsv
          enc: |
            -----BEGIN AGE ENCRYPTED FILE-----
            YWdlLWVuY3J5cHRpb24ub3JnL3YxCi0+IFgyNTUxOSA0b3NHNHpRTHExOW0zTEdv
            dVpScG1TbkJPUFA3cHM0RVZjM2luS0ErLzJnClk1UFpBZTBDZkNkM1V3bU8zTlBO
            OEdxNHBpT1hMYWxiVk9laTlOTTRUQ0kKLS0tIEtRWnA3TWIzejFYY3hLYVhuSVNl
            Q3JIZXZxVTRBWDNsWERtaWtkbkZ6QzgKrDaS8ko8o2oabyyCnZOATQpUox1aiSiJ
            GGGsiiyfKsv6z7ysXZHE5ytXVV22ehaHrBrZbep1SQ/mHludWCguHA==
            -----END AGE ENCRYPTED FILE-----
    lastmodified: "2025-12-31T14:46:45Z"
    mac: ENC[AES256_GCM,data:glQW23Smik4IyieglW4iKXumYGNe0i0CKoyDwGpaeCYw/ENE7abGqSFwC5zdBL8keBEFu2VucSCyQIT07aO/hKM/f2+Xg2XWBsqf8kNVCt0QusUqJ1hfm/Bxk3f+lTpO5xWBiFvv7ip2BOdIyJDLYT1R6N/xGyZou2AVgrDbxyk=,iv:oiWI8LjaSH4kyIu1F1qUtVAAzcWoEzpYVbBPqiD7nwc=,tag:iY6yKnDwpYxNiN9E/FMrKg==,type:str]
    encrypted_regex: ^(data|stringData)$
    mac_only_encrypted: true
    version: 3.11.0
