---
# yaml-language-server: $schema=https://datreeio.github.io/CRDs-catalog/gateway.envoyproxy.io/backend_v1alpha1.json
apiVersion: gateway.envoyproxy.io/v1alpha1
kind: Backend
metadata:
  labels:
    app.kubernetes.io/instance: home-assistant
    app.kubernetes.io/name: home-assistant
  name: home-assistant
spec:
  appProtocols:
    - gateway.envoyproxy.io/ws
    - gateway.envoyproxy.io/wss
  endpoints:
    - ip:
        address: 10.1.1.67
        port: 8123